from tkinter import *
def addition():
    str1=e1.get()
    str2=e2.get()
    str3=int(e1.get())+int(e2.get())
    str3=str(str3)
    e3.delete(0,END)
    e3.insert(0,str3)
def sub():
    str1=e1.get()
    str2=e2.get()
    str3=int(e1.get())-int(e2.get())
    str3=str(str3)
    e3.delete(0,END)
    e3.insert(0,str3)
def multi():
    str1=e1.get()
    str2=e2.get()
    str3=int(e1.get())*int(e2.get())
    str3=str(str3)

    e3.delete(0,END)
    e3.insert(0,str3)
def div():
    str1=e1.get()
    str2=e2.get()
    str3=int(e1.get())/int(e2.get())
    str3=str(str3)
    e3.delete(0,END)
    e3.insert(0,str3)
root=Tk()
root.title("Arithmetic Operations- Ganesha S")
f = Frame(root,height=350,width=500)
menubar=Menu(root)
root.config(menu=menubar)
filemenu=Menu(root,tearoff=0)
filemenu.add_command(label="Add",command=addition)
filemenu.add_command(label="Subtract",command=sub)
filemenu.add_command(label="Multiply",command=multi)
filemenu.add_command(label="Divide",command=div)
filemenu.add_separator()
filemenu.add_command(label="Exit",command=root.destroy)
menubar.add_cascade(label="Operations",menu=filemenu)
f.propagate(0)
f.pack()
e1=IntVar()
e2=IntVar()
e3=IntVar()
l1=Label(text='Enter first number:')
l2=Label(text='Enter second number:')
l3=Label(text='Result:')
e1=Entry(f,width=25,fg='white',bg='blue')
e2=Entry(f,width=25,fg='white',bg='blue')
e3=Entry(f,width=25,fg='white',bg='blue')
e3.pack()
l1.place(x=50,y=100)
e1.place(x=200,y=100)
l2.place(x=50,y=150)
l3.place(x=50,y=200)
e2.place(x=200,y=150)
e3.place(x=200,y=200)
root.mainloop()
